postShellHook = '''
echo Hello world
echo Place developer environment initialization commands here
'''

[programs]

bats = {}
curl = {}
unzip = {}

# Add additional packages. (use `flox search` to find more)
# docker = {}
# awscli2 = {}
# kubectl = {}

gnugrep = {}
which = {}
coreutils = {}

# Declarative vscode with specified extensions (an update requires running `flox update`)
#
# vscode = { extensions = ["ms-python.python", "ms-python.pylint"] }

# Declarative package with a specified version (an update requires running `flox update`)
#
# kubernetes-helm = { version = "3.7" }

# Example python with specified library versions
#
# [programs.python]
# python = "python39"
# requirements = '''
#     pip
#     allure-pytest==2.9.45
#     kubernetes
#     pytest
# '''
